// Package config reads and writes GOT's two YAML files:
//
//   - got.yml at the repo root — the project config that the user
//     commits to source control. It names the project, declares the
//     default branch and commit style, and lists enabled plugins.
//
//   - .got/config.yaml inside the .got/ directory — the per-repo
//     internal settings that the user does not need to see in their
//     editor. It is generated by `got init` and updated by the various
//     engines in later versions.
//
// See got-spec.md §5 for the full layout and §7 for the wizard that
// produces them.
package config

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ProjectConfig is the body of got.yml at the repo root.
type ProjectConfig struct {
	// Version is the config schema version. Always 1 in v0.1.
	Version int `yaml:"version"`
	// Project groups identity fields for the repository.
	Project ProjectMeta `yaml:"project"`
	// Commits groups commit-style settings.
	Commits CommitStyle `yaml:"commits"`
	// Plugins lists enabled plugins by name.
	Plugins PluginList `yaml:"plugins"`
	// AI selects the suggestion provider.
	AI AIConfig `yaml:"ai"`
}

// ProjectMeta is the project identity block.
type ProjectMeta struct {
	Name          string `yaml:"name"`
	DefaultBranch string `yaml:"default_branch"`
}

// CommitStyle controls how `got commit` validates messages.
type CommitStyle struct {
	// Style is "conventional", "freeform", or "custom".
	Style string `yaml:"style"`
	// CustomTemplate is a path to a template file, used when Style=custom.
	CustomTemplate string `yaml:"custom_template,omitempty"`
	// Scopes is the set of allowed scopes for conventional commits.
	// Empty means any scope is allowed.
	Scopes []string `yaml:"scopes"`
	// AllowBreaking toggles whether the "!" suffix / BREAKING CHANGE
	// footer is permitted in commit messages.
	AllowBreaking bool `yaml:"allow_breaking"`
}

// PluginList is the enabled-plugins block.
type PluginList struct {
	Enabled []string `yaml:"enabled"`
}

// AIConfig selects the suggestion provider. v0.1 only ships the
// heuristic provider; the field exists so v0.3+ can plug in others
// without a schema break.
type AIConfig struct {
	Provider string `yaml:"provider"`
}

// DefaultProjectConfig returns the v0.1 default ProjectConfig populated
// with reasonable defaults: conventional commits, no scopes, no
// plugins, heuristic AI, default_branch=main. The caller is expected
// to override fields based on the user's answers (or detected values).
func DefaultProjectConfig() ProjectConfig {
	return ProjectConfig{
		Version: 1,
		Project: ProjectMeta{
			Name:          "",
			DefaultBranch: "main",
		},
		Commits: CommitStyle{
			Style:         "conventional",
			Scopes:        []string{},
			AllowBreaking: true,
		},
		Plugins: PluginList{Enabled: []string{}},
		AI:      AIConfig{Provider: "heuristic"},
	}
}

// InternalConfig is the body of .got/config.yaml. v0.1 only carries
// the schema version; later versions will add theme, plugin timeouts,
// health thresholds, etc.
type InternalConfig struct {
	// Version is the internal config schema version. Always 1 in v0.1.
	Version int `yaml:"version"`
	// CreatedFrom is the GOT version that wrote this config.
	CreatedFrom string `yaml:"created_from"`
}

// DefaultInternalConfig returns the v0.1 default InternalConfig.
func DefaultInternalConfig(gotVersion string) InternalConfig {
	return InternalConfig{Version: 1, CreatedFrom: gotVersion}
}

// WriteProjectConfig writes cfg to path as YAML. The file is created
// with 0o644 permissions; intermediate directories are created with
// 0o755 if they don't already exist.
func WriteProjectConfig(path string, cfg ProjectConfig) error {
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal project config: %w", err)
	}
	return writeFile(path, body)
}

// ReadProjectConfig reads and parses a ProjectConfig from path.
func ReadProjectConfig(path string) (ProjectConfig, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return ProjectConfig{}, fmt.Errorf("read project config: %w", err)
	}
	var cfg ProjectConfig
	if err := yaml.Unmarshal(body, &cfg); err != nil {
		return ProjectConfig{}, fmt.Errorf("parse project config: %w", err)
	}
	return cfg, nil
}

// WriteInternalConfig writes cfg to path as YAML.
func WriteInternalConfig(path string, cfg InternalConfig) error {
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal internal config: %w", err)
	}
	return writeFile(path, body)
}

// ReadInternalConfig reads and parses an InternalConfig from path.
func ReadInternalConfig(path string) (InternalConfig, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return InternalConfig{}, fmt.Errorf("read internal config: %w", err)
	}
	var cfg InternalConfig
	if err := yaml.Unmarshal(body, &cfg); err != nil {
		return InternalConfig{}, fmt.Errorf("parse internal config: %w", err)
	}
	return cfg, nil
}

// FileExists is a small helper used by the init command to decide
// whether --force is required.
func FileExists(path string) (bool, error) {
	info, err := os.Stat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return !info.IsDir(), nil
}

// writeFile writes body to path, creating parent directories as
// needed. We avoid pulling in the cmd package; this is the only piece
// of "create parents" logic we need.
func writeFile(path string, body []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// ValidateCommitStyle returns an error if style is not one of the
// recognized values ("conventional", "freeform", "custom").
func ValidateCommitStyle(style string) error {
	switch strings.ToLower(style) {
	case "conventional", "freeform", "custom":
		return nil
	}
	return fmt.Errorf("invalid commit style %q (want conventional, freeform, or custom)", style)
}
